### ISSUE TITLE
cater for both gnome-control-center and budgie-control-center

### ISSUE THREAD

**Issue by fossfreedom** [samlane-ma/analogue-clock-applet#2]
Any chance that budgie-control-center can be invoked for the date-time settings if it is installed?

https://github.com/samlane-ma/analogue-clock-applet/blob/3f6d8b83527837a4ab990df84bfd6c33c153859a/src/analogue-clock-applet.vala#L370

This will save patching the code specifically for jammy and later.

TIA

**Comment by samlane-ma** [comment]
I appreciate you catching this.  It has been updated to use Budgie Control Center if it is present, and Gnome Control Center if not.

Thanks!
